services:
  - type: web
    name: gas-tracker-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gas-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: $PORT
      - key: DEBUG
        value: "False"
      - key: CORS_ORIGINS
        value: '["https://your-frontend-url.com"]'

databases:
  - name: gas-tracker-db
    databaseName: gas_tracker
    user: gas_tracker_user
    plan: free 